name: Build

on:
  push:
    branches: [ main, dev, feature/add-workflow-ci ]
  pull_request:
    branches: [ main, dev, feature/add-workflow-ci ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make -j4

      - name: Test
        run: |
          cd build
          ./ctrace --help

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake .. -DSKIP_ANALYSIS_TOOLS=ON -DBOOST_FROM_SCRIPT=ON

      - name: Build
        run: |
          cd build
          make ctrace

      - name: Test
        run: |
          cd build
          ./ctrace --help

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake .. -DSKIP_ANALYSIS_TOOLS=ON -DBOOST_FROM_SCRIPT=ON -G "Visual Studio 17 2022" -A x64

      - name: Build
        run: |
          cd build
          cmake --build . --config Release --target ctrace

      - name: Test
        run: |
          cd build\Release
          .\ctrace.exe --help